package com.ecommerce.constant;

/**
 * Notification Module Constants
 * Error Codes: E800-E849 (50 codes)
 * Success Codes: S800-S849 (50 codes)
 * 
 * Categories:
 * - E800-E809: Basic Operations (10 codes)
 * - E810-E819: Validation & Data (10 codes)
 * - E820-E829: User & Permission (10 codes)
 * - E830-E839: WebSocket & Connection (10 codes)
 * - E840-E849: Business Logic (10 codes)
 */
public class NotificationConstant {

    // ========== ERROR CODES ==========

    // Basic Operations (E800-E809)
    public static final String E800_NOTIFICATION_NOT_FOUND = "E800_NOTIFICATION_NOT_FOUND";
    public static final String E801_NOTIFICATION_CREATE_FAILED = "E801_NOTIFICATION_CREATE_FAILED";
    public static final String E802_NOTIFICATION_UPDATE_FAILED = "E802_NOTIFICATION_UPDATE_FAILED";
    public static final String E803_NOTIFICATION_DELETE_FAILED = "E803_NOTIFICATION_DELETE_FAILED";
    public static final String E804_NOTIFICATION_FETCH_FAILED = "E804_NOTIFICATION_FETCH_FAILED";
    public static final String E805_NOTIFICATION_SEND_FAILED = "E805_NOTIFICATION_SEND_FAILED";
    public static final String E806_NOTIFICATION_MARK_READ_FAILED = "E806_NOTIFICATION_MARK_READ_FAILED";
    public static final String E807_NOTIFICATION_MARK_ALL_READ_FAILED = "E807_NOTIFICATION_MARK_ALL_READ_FAILED";
    public static final String E808_NOTIFICATION_BATCH_DELETE_FAILED = "E808_NOTIFICATION_BATCH_DELETE_FAILED";
    public static final String E809_NOTIFICATION_CLEAR_ALL_FAILED = "E809_NOTIFICATION_CLEAR_ALL_FAILED";

    // Validation & Data (E810-E819)
    public static final String E810_NOTIFICATION_INVALID_TYPE = "E810_NOTIFICATION_INVALID_TYPE";
    public static final String E811_NOTIFICATION_INVALID_DATA = "E811_NOTIFICATION_INVALID_DATA";
    public static final String E812_NOTIFICATION_MISSING_RECIPIENT = "E812_NOTIFICATION_MISSING_RECIPIENT";
    public static final String E813_NOTIFICATION_MISSING_CONTENT = "E813_NOTIFICATION_MISSING_CONTENT";
    public static final String E814_NOTIFICATION_INVALID_PRIORITY = "E814_NOTIFICATION_INVALID_PRIORITY";
    public static final String E815_NOTIFICATION_EXPIRED = "E815_NOTIFICATION_EXPIRED";
    public static final String E816_NOTIFICATION_ALREADY_READ = "E816_NOTIFICATION_ALREADY_READ";
    public static final String E817_NOTIFICATION_INVALID_FILTER = "E817_NOTIFICATION_INVALID_FILTER";
    public static final String E818_NOTIFICATION_INVALID_SORT = "E818_NOTIFICATION_INVALID_SORT";
    public static final String E819_NOTIFICATION_INVALID_PAGINATION = "E819_NOTIFICATION_INVALID_PAGINATION";

    // User & Permission (E820-E829)
    public static final String E820_NOTIFICATION_USER_NOT_FOUND = "E820_NOTIFICATION_USER_NOT_FOUND";
    public static final String E821_NOTIFICATION_ACCESS_DENIED = "E821_NOTIFICATION_ACCESS_DENIED";
    public static final String E822_NOTIFICATION_NOT_OWNER = "E822_NOTIFICATION_NOT_OWNER";
    public static final String E823_NOTIFICATION_INVALID_ROLE = "E823_NOTIFICATION_INVALID_ROLE";
    public static final String E824_NOTIFICATION_USER_BLOCKED = "E824_NOTIFICATION_USER_BLOCKED";
    public static final String E825_NOTIFICATION_PERMISSION_REQUIRED = "E825_NOTIFICATION_PERMISSION_REQUIRED";
    public static final String E826_NOTIFICATION_ADMIN_ONLY = "E826_NOTIFICATION_ADMIN_ONLY";
    public static final String E827_NOTIFICATION_UNAUTHORIZED = "E827_NOTIFICATION_UNAUTHORIZED";
    public static final String E828_NOTIFICATION_SESSION_EXPIRED = "E828_NOTIFICATION_SESSION_EXPIRED";
    public static final String E829_NOTIFICATION_TOKEN_INVALID = "E829_NOTIFICATION_TOKEN_INVALID";

    // WebSocket & Connection (E830-E839)
    public static final String E830_WEBSOCKET_CONNECTION_FAILED = "E830_WEBSOCKET_CONNECTION_FAILED";
    public static final String E831_WEBSOCKET_SEND_FAILED = "E831_WEBSOCKET_SEND_FAILED";
    public static final String E832_WEBSOCKET_NOT_CONNECTED = "E832_WEBSOCKET_NOT_CONNECTED";
    public static final String E833_WEBSOCKET_SUBSCRIBE_FAILED = "E833_WEBSOCKET_SUBSCRIBE_FAILED";
    public static final String E834_WEBSOCKET_UNSUBSCRIBE_FAILED = "E834_WEBSOCKET_UNSUBSCRIBE_FAILED";
    public static final String E835_WEBSOCKET_SESSION_NOT_FOUND = "E835_WEBSOCKET_SESSION_NOT_FOUND";
    public static final String E836_WEBSOCKET_DISCONNECT_FAILED = "E836_WEBSOCKET_DISCONNECT_FAILED";
    public static final String E837_WEBSOCKET_BROADCAST_FAILED = "E837_WEBSOCKET_BROADCAST_FAILED";
    public static final String E838_WEBSOCKET_CHANNEL_ERROR = "E838_WEBSOCKET_CHANNEL_ERROR";
    public static final String E839_WEBSOCKET_MESSAGE_TOO_LARGE = "E839_WEBSOCKET_MESSAGE_TOO_LARGE";

    // Business Logic (E840-E849)
    public static final String E840_NOTIFICATION_TEMPLATE_NOT_FOUND = "E840_NOTIFICATION_TEMPLATE_NOT_FOUND";
    public static final String E841_NOTIFICATION_RATE_LIMIT_EXCEEDED = "E841_NOTIFICATION_RATE_LIMIT_EXCEEDED";
    public static final String E842_NOTIFICATION_DUPLICATE = "E842_NOTIFICATION_DUPLICATE";
    public static final String E843_NOTIFICATION_BATCH_LIMIT_EXCEEDED = "E843_NOTIFICATION_BATCH_LIMIT_EXCEEDED";
    public static final String E844_NOTIFICATION_QUEUE_FULL = "E844_NOTIFICATION_QUEUE_FULL";
    public static final String E845_NOTIFICATION_PROCESSING_ERROR = "E845_NOTIFICATION_PROCESSING_ERROR";
    public static final String E846_NOTIFICATION_DELIVERY_FAILED = "E846_NOTIFICATION_DELIVERY_FAILED";
    public static final String E847_NOTIFICATION_SCHEDULE_FAILED = "E847_NOTIFICATION_SCHEDULE_FAILED";
    public static final String E848_NOTIFICATION_RETRY_EXHAUSTED = "E848_NOTIFICATION_RETRY_EXHAUSTED";
    public static final String E849_NOTIFICATION_SERVICE_UNAVAILABLE = "E849_NOTIFICATION_SERVICE_UNAVAILABLE";

    // ========== SUCCESS CODES ==========

    // Basic Operations (S800-S809)
    public static final String S800_NOTIFICATION_FOUND = "S800_NOTIFICATION_FOUND";
    public static final String S801_NOTIFICATION_CREATED = "S801_NOTIFICATION_CREATED";
    public static final String S802_NOTIFICATION_UPDATED = "S802_NOTIFICATION_UPDATED";
    public static final String S803_NOTIFICATION_DELETED = "S803_NOTIFICATION_DELETED";
    public static final String S804_NOTIFICATION_LIST_FETCHED = "S804_NOTIFICATION_LIST_FETCHED";
    public static final String S805_NOTIFICATION_SENT = "S805_NOTIFICATION_SENT";
    public static final String S806_NOTIFICATION_MARKED_READ = "S806_NOTIFICATION_MARKED_READ";
    public static final String S807_NOTIFICATION_ALL_MARKED_READ = "S807_NOTIFICATION_ALL_MARKED_READ";
    public static final String S808_NOTIFICATION_BATCH_DELETED = "S808_NOTIFICATION_BATCH_DELETED";
    public static final String S809_NOTIFICATION_ALL_CLEARED = "S809_NOTIFICATION_ALL_CLEARED";

    // Query Operations (S810-S819)
    public static final String S810_NOTIFICATION_UNREAD_COUNT_FETCHED = "S810_NOTIFICATION_UNREAD_COUNT_FETCHED";
    public static final String S811_NOTIFICATION_RECENT_FETCHED = "S811_NOTIFICATION_RECENT_FETCHED";
    public static final String S812_NOTIFICATION_BY_TYPE_FETCHED = "S812_NOTIFICATION_BY_TYPE_FETCHED";
    public static final String S813_NOTIFICATION_BY_DATE_FETCHED = "S813_NOTIFICATION_BY_DATE_FETCHED";
    public static final String S814_NOTIFICATION_SEARCH_COMPLETED = "S814_NOTIFICATION_SEARCH_COMPLETED";
    public static final String S815_NOTIFICATION_FILTER_APPLIED = "S815_NOTIFICATION_FILTER_APPLIED";
    public static final String S816_NOTIFICATION_SORTED = "S816_NOTIFICATION_SORTED";
    public static final String S817_NOTIFICATION_PAGE_FETCHED = "S817_NOTIFICATION_PAGE_FETCHED";
    public static final String S818_NOTIFICATION_STATISTICS_FETCHED = "S818_NOTIFICATION_STATISTICS_FETCHED";
    public static final String S819_NOTIFICATION_HISTORY_FETCHED = "S819_NOTIFICATION_HISTORY_FETCHED";

    // WebSocket Operations (S820-S829)
    public static final String S820_WEBSOCKET_CONNECTED = "S820_WEBSOCKET_CONNECTED";
    public static final String S821_WEBSOCKET_DISCONNECTED = "S821_WEBSOCKET_DISCONNECTED";
    public static final String S822_WEBSOCKET_SUBSCRIBED = "S822_WEBSOCKET_SUBSCRIBED";
    public static final String S823_WEBSOCKET_UNSUBSCRIBED = "S823_WEBSOCKET_UNSUBSCRIBED";
    public static final String S824_WEBSOCKET_MESSAGE_SENT = "S824_WEBSOCKET_MESSAGE_SENT";
    public static final String S825_WEBSOCKET_BROADCAST_SENT = "S825_WEBSOCKET_BROADCAST_SENT";
    public static final String S826_WEBSOCKET_SESSION_ACTIVE = "S826_WEBSOCKET_SESSION_ACTIVE";
    public static final String S827_WEBSOCKET_PING_SUCCESS = "S827_WEBSOCKET_PING_SUCCESS";
    public static final String S828_WEBSOCKET_RECONNECTED = "S828_WEBSOCKET_RECONNECTED";
    public static final String S829_WEBSOCKET_HEARTBEAT_OK = "S829_WEBSOCKET_HEARTBEAT_OK";

    // Business Operations (S830-S839)
    public static final String S830_NOTIFICATION_BROADCAST_SUCCESS = "S830_NOTIFICATION_BROADCAST_SUCCESS";
    public static final String S831_NOTIFICATION_ROLE_SENT = "S831_NOTIFICATION_ROLE_SENT";
    public static final String S832_NOTIFICATION_USER_SENT = "S832_NOTIFICATION_USER_SENT";
    public static final String S833_NOTIFICATION_SCHEDULED = "S833_NOTIFICATION_SCHEDULED";
    public static final String S834_NOTIFICATION_RETRY_SUCCESS = "S834_NOTIFICATION_RETRY_SUCCESS";
    public static final String S835_NOTIFICATION_DELIVERED = "S835_NOTIFICATION_DELIVERED";
    public static final String S836_NOTIFICATION_PREFERENCES_UPDATED = "S836_NOTIFICATION_PREFERENCES_UPDATED";
    public static final String S837_NOTIFICATION_TEMPLATE_APPLIED = "S837_NOTIFICATION_TEMPLATE_APPLIED";
    public static final String S838_NOTIFICATION_BATCH_PROCESSED = "S838_NOTIFICATION_BATCH_PROCESSED";
    public static final String S839_NOTIFICATION_QUEUE_CLEARED = "S839_NOTIFICATION_QUEUE_CLEARED";

    // System (S840-S849)
    public static final String S840_NOTIFICATION_SYSTEM_READY = "S840_NOTIFICATION_SYSTEM_READY";
    public static final String S841_NOTIFICATION_HEALTH_CHECK_OK = "S841_NOTIFICATION_HEALTH_CHECK_OK";
    public static final String S842_NOTIFICATION_CACHE_CLEARED = "S842_NOTIFICATION_CACHE_CLEARED";
    public static final String S843_NOTIFICATION_CONFIG_UPDATED = "S843_NOTIFICATION_CONFIG_UPDATED";
    public static final String S844_NOTIFICATION_BACKUP_CREATED = "S844_NOTIFICATION_BACKUP_CREATED";
    public static final String S845_NOTIFICATION_RESTORED = "S845_NOTIFICATION_RESTORED";
    public static final String S846_NOTIFICATION_MIGRATED = "S846_NOTIFICATION_MIGRATED";
    public static final String S847_NOTIFICATION_OPTIMIZED = "S847_NOTIFICATION_OPTIMIZED";
    public static final String S848_NOTIFICATION_CLEANUP_COMPLETED = "S848_NOTIFICATION_CLEANUP_COMPLETED";
    public static final String S849_NOTIFICATION_MAINTENANCE_DONE = "S849_NOTIFICATION_MAINTENANCE_DONE";
}
